export const TELEMETRY_WINDOW_DAYS = 30;
export const GITHUB_REQUEST_TIMEOUT_MS = 15_000;
export const AI_REQUEST_TIMEOUT_MS = 8_000;
export const AI_TOTAL_TIMEOUT_MS = 30_000;

export const STALE_ISSUE_THRESHOLD_DAYS = 14;
export const STALE_PR_THRESHOLD_DAYS = 7;

export const SCORING_THRESHOLDS = {
  CODE_HEALTH_BASE: 95,
  BUG_FIX_PENALTY_WEIGHT: 60,
  CHURN_HIGH_THRESHOLD: 250,
  CHURN_HIGH_PENALTY: 15,
  CHURN_MEDIUM_THRESHOLD: 150,
  CHURN_MEDIUM_PENALTY: 8,
  DELIVERY_BASE_SCORE: 50,
  DELIVERY_ACTIVE_DAY_WEIGHT: 4.5,
  MAINTENANCE_OPEN_HIGH_RATIO: 0.4,
  MAINTENANCE_OPEN_HIGH_PENALTY: 25,
  MAINTENANCE_OPEN_MEDIUM_RATIO: 0.2,
  MAINTENANCE_OPEN_MEDIUM_PENALTY: 10,
} as const;

